repos:
  - repo: local
    hooks:
      - id: terraform-pre-commit
        name: Run terraform/.pre-commit-config.yaml
        entry: bash -c 'cd terraform && pre-commit run --all-files'
        language: system
        pass_filenames: false
