repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c 'gofmt -s -w $(find . -type f -name "*.go")'
        language: system
        types: [go]
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'cd apps/authify && golangci-lint run ./...'
        language: system
        types: [go]
        pass_filenames: false
